$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

settings:
  default_compute: azureml:LAB4

inputs:
  sampled_data:
    type: uri_folder
    path: azureml:amazon_electronics_features_v1_sampled@latest

jobs:
  split:
    type: command
    component: azureml:split_dataset@latest
    inputs:
      data: ${{parent.inputs.sampled_data}}
      seed: 42
      train_ratio: 0.60
      val_ratio: 0.15
      test_ratio: 0.15
      deploy_ratio: 0.10
    outputs:
      train: {}
      val: {}
      test: {}
      deploy: {}

  normalize_train:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.train}}
    outputs:
      out: {}

  normalize_val:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.val}}
    outputs:
      out: {}

  normalize_test:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.test}}
    outputs:
      out: {}

  normalize_deploy:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.deploy}}
    outputs:
      out: {}

  length_train:
    type: command
    component: azureml:review_length_features@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  length_val:
    type: command
    component: azureml:review_length_features@latest
    inputs:
      data: ${{parent.jobs.normalize_val.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  length_test:
    type: command
    component: azureml:review_length_features@latest
    inputs:
      data: ${{parent.jobs.normalize_test.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  length_deploy:
    type: command
    component: azureml:review_length_features@latest
    inputs:
      data: ${{parent.jobs.normalize_deploy.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sentiment_train:
    type: command
    component: azureml:vader_sentiment_features@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sentiment_val:
    type: command
    component: azureml:vader_sentiment_features@latest
    inputs:
      data: ${{parent.jobs.normalize_val.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sentiment_test:
    type: command
    component: azureml:vader_sentiment_features@latest
    inputs:
      data: ${{parent.jobs.normalize_test.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sentiment_deploy:
    type: command
    component: azureml:vader_sentiment_features@latest
    inputs:
      data: ${{parent.jobs.normalize_deploy.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  tfidf_fit_train:
    type: command
    component: azureml:tfidf_fit@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
      text_col: reviewText
      max_features: 500
      ngram_max: 1
    outputs:
      model_out: {}

  tfidf_train:
    type: command
    component: azureml:tfidf_transform@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
      model_dir: ${{parent.jobs.tfidf_fit_train.outputs.model_out}}
      text_col: reviewText
    outputs:
      out: {}

  tfidf_val:
    type: command
    component: azureml:tfidf_transform@latest
    inputs:
      data: ${{parent.jobs.normalize_val.outputs.out}}
      model_dir: ${{parent.jobs.tfidf_fit_train.outputs.model_out}}
      text_col: reviewText
    outputs:
      out: {}

  tfidf_test:
    type: command
    component: azureml:tfidf_transform@latest
    inputs:
      data: ${{parent.jobs.normalize_test.outputs.out}}
      model_dir: ${{parent.jobs.tfidf_fit_train.outputs.model_out}}
      text_col: reviewText
    outputs:
      out: {}

  tfidf_deploy:
    type: command
    component: azureml:tfidf_transform@latest
    inputs:
      data: ${{parent.jobs.normalize_deploy.outputs.out}}
      model_dir: ${{parent.jobs.tfidf_fit_train.outputs.model_out}}
      text_col: reviewText
    outputs:
      out: {}

  sbert_train:
    type: command
    component: azureml:sbert_embeddings@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sbert_val:
    type: command
    component: azureml:sbert_embeddings@latest
    inputs:
      data: ${{parent.jobs.normalize_val.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sbert_test:
    type: command
    component: azureml:sbert_embeddings@latest
    inputs:
      data: ${{parent.jobs.normalize_test.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  sbert_deploy:
    type: command
    component: azureml:sbert_embeddings@latest
    inputs:
      data: ${{parent.jobs.normalize_deploy.outputs.out}}
      text_col: reviewText
    outputs:
      out: {}

  merge_train:
    type: command
    component: azureml:merge_features@latest
    inputs:
      base: ${{parent.jobs.normalize_train.outputs.out}}
      length: ${{parent.jobs.length_train.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_train.outputs.out}}
      tfidf: ${{parent.jobs.tfidf_train.outputs.out}}
      sbert: ${{parent.jobs.sbert_train.outputs.out}}
      key1: asin
      key2: reviewerID
    outputs:
      out: {}

  merge_val:
    type: command
    component: azureml:merge_features@latest
    inputs:
      base: ${{parent.jobs.normalize_val.outputs.out}}
      length: ${{parent.jobs.length_val.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_val.outputs.out}}
      tfidf: ${{parent.jobs.tfidf_val.outputs.out}}
      sbert: ${{parent.jobs.sbert_val.outputs.out}}
      key1: asin
      key2: reviewerID
    outputs:
      out: {}

  merge_test:
    type: command
    component: azureml:merge_features@latest
    inputs:
      base: ${{parent.jobs.normalize_test.outputs.out}}
      length: ${{parent.jobs.length_test.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_test.outputs.out}}
      tfidf: ${{parent.jobs.tfidf_test.outputs.out}}
      sbert: ${{parent.jobs.sbert_test.outputs.out}}
      key1: asin
      key2: reviewerID
    outputs:
      out: {}

  merge_deploy:
    type: command
    component: azureml:merge_features@latest
    inputs:
      base: ${{parent.jobs.normalize_deploy.outputs.out}}
      length: ${{parent.jobs.length_deploy.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_deploy.outputs.out}}
      tfidf: ${{parent.jobs.tfidf_deploy.outputs.out}}
      sbert: ${{parent.jobs.sbert_deploy.outputs.out}}
      key1: asin
      key2: reviewerID
    outputs:
      out: {}